AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'app/assets/**/*'
    - 'app/channels/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config.ru'